bharathkumarraju@R77-NB193 ami_filter % packer build ubuntu_ami_filter.json
amazon-ebs: output will be in this color.

==> amazon-ebs: Prevalidating any provided VPC information
==> amazon-ebs: Prevalidating AMI Name: packer  1592347772
    amazon-ebs: Found Image ID: ami-04781752c9b20ea41
==> amazon-ebs: Creating temporary keypair: packer_5ee94c7c-2110-6191-877e-d7f742aa5352
==> amazon-ebs: Creating temporary security group for this instance: packer_5ee94c82-6dff-dcdf-d82b-870234b43f28
==> amazon-ebs: Authorizing access to port 22 from [0.0.0.0/0] in the temporary security groups...
==> amazon-ebs: Launching a source AWS instance...
==> amazon-ebs: Adding tags to source instance
    amazon-ebs: Adding tag: "Name": "Packer Builder"
    amazon-ebs: Instance ID: i-06f623b7bf7d95ad0
==> amazon-ebs: Waiting for instance (i-06f623b7bf7d95ad0) to become ready...
==> amazon-ebs: Using ssh communicator to connect: 18.188.10.255
==> amazon-ebs: Waiting for SSH to become available...
==> amazon-ebs: Connected to SSH!
==> amazon-ebs: Stopping the source instance...
    amazon-ebs: Stopping instance
==> amazon-ebs: Waiting for the instance to stop...
==> amazon-ebs: Creating AMI packer  1592347772 from instance i-06f623b7bf7d95ad0
    amazon-ebs: AMI: ami-0e238da14e53ec942
==> amazon-ebs: Waiting for AMI to become ready...
==> amazon-ebs: Terminating the source AWS instance...
==> amazon-ebs: Cleaning up any extra volumes...
==> amazon-ebs: No volumes to clean up, skipping
==> amazon-ebs: Deleting temporary security group...
==> amazon-ebs: Deleting temporary keypair...
Build 'amazon-ebs' finished.

==> Builds finished. The artifacts of successful builds are:
--> amazon-ebs: AMIs were created:
us-east-2: ami-0e238da14e53ec942

bharathkumarraju@R77-NB193 ami_filter %
