---
- name: Install jenkins
  hosts: all
  become: true
  vars:
    ssh_use_pam: true # to allow access with our key on ec2
    jenkins_hostname: localhost
    ansible_remote_tmp: /tmp/ansible
    jenkins_plugins: [ansicolor]

  roles:
    - geerlingguy.java
    - geerlingguy.jenkins
    - wcm_io_devops.jenkins_pipeline_library
    - geerlingguy.packer
    - geerlingguy.ansible
